# Fabric Properties
minecraft_version=1.18.2
yarn_mappings=1.18.2+build.4
loader_version=0.17.3

# Mod Properties
mod_version=2.2.9
maven_group=com.atsukigames
archives_base_name=playerdataconnector
mod_id=playerdataconnector

# Dependencies
fabric_version=0.77.0+1.18.2

# Gradle設定
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
